provider:
  name: cloudflare

env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare
        key: token

sources:
  - ingress
  - gateway-httproute
  - gateway-grpcroute

policy: sync

extraArgs:
  - --cloudflare-proxied
  - --cloudflare-dns-records-per-page=5000
