apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: production-apps
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: "*"
      useAnnotations: true
