global:
  extraEnvFrom:
    - secretRef:
        name: mimir-s3-credentials
mimir:
  structuredConfig:
    memberlist:
      cluster_label: "mimir"
      cluster_label_verification_disabled: false
    server:
      log_level: info
      grpc_server_max_recv_msg_size: 104857600
      grpc_server_max_send_msg_size: 104857600
      grpc_server_max_concurrent_streams: 1000
    limits:
      max_label_names_per_series: 120
      max_global_series_per_user: 12000000
      ingestion_burst_size: 200000
      ingestion_rate: 150000
      max_global_series_per_metric: 200000000
      compactor_blocks_retention_period: 24h
    blocks_storage:
      backend: s3
      s3:
        endpoint: "88637849b2895815e424609442014ce3.r2.cloudflarestorage.com"
        access_key_id: "${R2_ACCESS_KEY_ID}"
        secret_access_key: "${R2_SECRET_ACCESS_KEY}"
        bucket_name: "mimir"
    compactor:
      compaction_interval: 2h
    query_scheduler:
      max_outstanding_requests_per_tenant: 10000
ingester:
  zoneAwareReplication:
    enabled: false
  persistentVolume:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 5Gi
  replicas: 2
distributor:
  extraArgs:
    auth.multitenancy-enabled: false
    log.level: info
  replicas: 1
compactor:
  replicas: 1
querier:
  replicas: 2
query_frontend:
  replicas: 1
query_scheduler:
  replicas: 1
store_gateway:
  zoneAwareReplication:
    enabled: false
  replicas: 1
rollout_operator:
  enabled: false
ruler:
  enabled: false
overrides_exporter:
  enabled: false
alertmanager:
  enabled: false
minio:
  enabled: false
metaMonitoring:
  dashboards:
    enabled: true
    annotations:
      grafana_folder: "Mimir"
  serviceMonitor:
    enabled: true
kafka:
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
